spring:
  application:
    name: configuration
  datasource:
    url: localhost:3306
    name: config
    username: app_user
    password: secret
    driver-class-name: com.mysql.jdbc.Driver
  docker:
    compose:
          enabled: false
